"""added a join table for posts and tags

Revision ID: 023191f9596a
Revises: afdff3a51c16
Create Date: 2024-09-28 19:19:39.556392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023191f9596a'
down_revision = 'afdff3a51c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tag')
    # ### end Alembic commands ###
