"""added relationships in user model for likes, followers, and bookmarks

Revision ID: 32a16fb7d426
Revises: 023191f9596a
Create Date: 2024-09-28 19:35:22.533777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a16fb7d426'
down_revision = '023191f9596a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_table('bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('following_count', sa.Integer(), nullable=True))
        batch_op.drop_column('following')
        batch_op.drop_column('followers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('following', sa.INTEGER(), nullable=True))
        batch_op.drop_column('following_count')
        batch_op.drop_column('follower_count')

    op.drop_table('likes')
    op.drop_table('bookmarks')
    op.drop_table('followers')
    # ### end Alembic commands ###
