"""empty message

Revision ID: ec71c61c3b58
Revises: 9556ccf0f45b
Create Date: 2024-09-28 13:04:06.748758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec71c61c3b58'
down_revision = '9556ccf0f45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('batch')

    # ### end Alembic commands ###
